### ISSUE TITLE
Closing / enabling interactive mode doesn't update inside/outside

### ISSUE THREAD

**Issue by mirlip** [s-leger/blenderPolygons#11] opened 2017-05-16 15:16 UTC
When drawing a wall, it's easier to choose the way you do it, clock-wise or counter-clock-wise. The inside and outside could be determined automatically when closing.
At the moment, if I trust the windows direction when clicking interactive mode, the inside/outside are predefined on first click. It results in windows rotated 180°.

**Comment by s-leger** [comment] 2017-05-16 20:03
Window direction depends on the orientation primary to boolean operation.
To estimate orientation, i do take a point 1 m behind window, and check if he's on left or right part of the wall's side you draw (side showing manipulators).

With perpendicular window at boolean time, they likely to rotate the wrong side (and as long as there is nearly no way to determine inside/outside from say unclosed wall, if you lucky they rotate the right side).  
A linear analysis to see witch side is the longest may be part of the solution, but you'll always find edges cases where it fails.  
 
So i must find a better way to determine default rotation.  

Also such rule dosen't work with doors as opening direction may vary.  

Seem logical to draw external part of the wall, but cant assume it will always be the case, and not enforce any CW or CCW way of drawing to set inside or outside.  
Anothe issue is interoperability as some data-models use axis to define a wall.

There are then 2 set of params to handle inside/outside materials and drawing from borders or axis.
* Inside / Outside for material, currently does affect windows and doors holes materials according too,
* Offset from -1 to 1 to allow drawing from either border and axis.

**Comment by mirlip** [comment] 2017-05-16 20:39
As I'm not a native english speaker, to clarify:
- for closed walls, we agree the solution can be automatic?
- for other wall, user can define the inside/outside with the flip option. It could be used to rotate windows and such according to this? For cases where both direction make sens, they could also get a flip option.

**Comment by s-leger** [comment] 2017-05-16 20:57
At draw a wall time, and when closing a wall, 
we may assume wich part is the inside and set flip when relevant.

At manipulate time, and boolean use the flip param to determine witch side is inside/outside and orient window according.

**Comment by s-leger** [comment] 2017-05-17 23:12
Fixed : 
Window auto align to outside at boolean time, and when flip does change.
Full support for x_offset added too.

**Closed by s-leger** 2017-05-17 23:12 UTC
